######################################
# Basic telescope setup. Change here #
######################################

# telescope host name
host = "Gavin-Telescope"

# host machine data paths, ensure these folders exist
calibration_root_host = "C:\\Users\\itelescope\\Dropbox\\MoanaSSO\\DonutsCalibration"
logging_root_host = "C:\\Users\\itelescope\\Dropbox\\MoanaSSO\\DonutsLog"
data_root_host = "C:\\Users\\itelescope\\Dropbox\\MoanaSSO"
reference_root_host = "C:\\Users\\itelescope\\Dropbox\\MoanaSSO\\DonutsReference"

# fits image characteristics
image_extension = ".FIT"
filter_keyword = "FILTER"
field_keyword = "OBJECT"
ra_keyword = "OBJCTRA"
dec_keyword = "OBJCTDEC"
xbin_keyword = "XBINNING"
ybin_keyword = "YBINNING"
xsize_keyword = "NAXIS1"
ysize_keyword = "NAXIS2"
xorigin_keyword = "XORGSUBF"
yorigin_keyword = "YORGSUBF"

# image masking - supply this to mask bad columns etc
# remove this entry to skip image masking. This file must be stored
# in the DonutsCalibration directory
#full_frame_boolean_mask_file = "full_frame_mask.fits"

# logging info
# level of logging detail, choices: "info" or "debug"
logging_level = "info"
# location of log output, choices: "file" or "stdout"
logging_location = "file"

# donuts algorithm info
donuts_subtract_bkg = true

#########################################
# Change this section after calibration #
#########################################

# calibration settings
calibration_filter_index = 3
calibration_binning = 3

# guiding characteristics
ra_axis = "y"

mount_type = "FORK"
#pixels_to_time = {"+x" = 61.65, "-x" = 62.45, "+y" = 72.27, "-y" = 72.62}
#guide_directions = {"+y" = 3, "-y" = 2, "+x" = 0, "-x" = 1}
pixels_to_time = {"+y" = 26.01, "-y" = 26.13, "+x" = 26.03, "-x" = 25.96}
guide_directions = {"+y" = 0, "-y" = 1, "+x" = 2, "-x" = 3}

######################################################
# DO NOT CHANGE INFO BELOW HERE UNLESS INSTRUCTED TO #
######################################################

# voyager info
socket_ip = "host.docker.internal"
socket_port = 5950

# docker data paths
calibration_root = "/voyager_calibration"
logging_root = "/voyager_log"
data_root = "/voyager_data"
reference_root = "/voyager_reference"

# calibration setup
calibration_step_size_ms = 5000
calibration_n_iterations = 5
calibration_exptime = 20

# guiding PID/stats setup
guide_buffer_length = 20
guide_buffer_sigma = 10
max_error_pixels = 20
n_images_to_stabilise = 10
stabilised_pixel_shift = 2
pid_coeffs.x.p=0.75
pid_coeffs.x.i=0.02
pid_coeffs.x.d=0.0
pid_coeffs.y.p=0.7
pid_coeffs.y.i=0.02
pid_coeffs.y.d=0.0
pid_coeffs.set_x = 0.0
pid_coeffs.set_y = 0.0
